spring:
  profiles:
    active: default

---

spring:
  config:
    activate:
      on-profile: default
server:
  port: 9443
  ssl:
    key-store: ssl/server/keystore.p12
    key-store-password: abc123
    key-alias: server
    client-auth: need
    trust-store: ssl/server/truststore_both.p12
    trust-store-password: abc123
